In [5]:
import numpy as np

states = ["1q", "2q", "3q"]
initial_prob = [0.9, 0.1, 0 ]
A = [[0.5,0.3,0.2],
    [0,0.6,0.4],
    [0,0,1]]
B = [[0.7, 0.3],
    [0.4, 0.6],
    [0.8, 0.2]]
observation_seq = [1,2,1,2]      

In [6]:
def emissionProb(state_id, observation):
    result = B[state_id][observation-1]
    return result

In [9]:
def HMM(states, initial_prob, B, observation_seq, A):
    
    table = np.zeros((len(states),len(observation_seq)))
    back_trace_table = np.zeros((len(states),len(observation_seq)))
    
    #Initialization
    for i in range(len(states)):
        table[i][0] = initial_prob[i]*emissionProb(i,observation_seq[0])
    #*******************************************************************
    
    #Forward Algorithm - Recursion
    for observation_id in range(1,len(observation_seq),1):

        for state_id in range(len(states)):
            
            paths = []
           
            for path_id in range(len(states)):
                element1 = table[path_id][observation_id-1]
                element2 = A[path_id][state_id]
                element3 = emissionProb(state_id, observation_seq[observation_id])
                path_element = element1*element2*element3
                paths.append(path_element)

            table[state_id][observation_id] = sum(paths)
            back_trace_table[state_id][observation_id] = np.argmax(paths)

    #Viterbi Decoding****************************************************
    max_state_id = int(np.argmax(table[:,-1]))     #son sütundaki maximum değere sahip sayının state idsi
    state_pointer = int(back_trace_table[max_state_id][-1])
    inverse_best_seq = states[max_state_id]

    for observation_id in range(len(observation_seq)-2,-1,-1):
        inverse_best_seq += states[state_pointer]
        state_pointer = int(back_trace_table[state_pointer][observation_id])
    
    best_sequence = inverse_best_seq[::-1]
    #print("inverse best seq", inverse_best_seq)
    
    prob = [table[i][-1] for i in range(table.shape[0])]
    probability_of_observation_seq = sum(prob)
    
    print("Forward table:\n",table)
    print("**************************************************")
    print("Backtrace Table:\n",back_trace_table)
    print("**************************************************")
    print("Best Hidden Sequence",best_sequence)
    print("**************************************************")
    print("Probability of Observation Sequence:",probability_of_observation_seq)
    
    return probability_of_observation_seq, best_sequence

probability_of_observation_seq, best_sequence = HMM(states, initial_prob, B, observation_seq, A)

Forward table:
 [[0.63       0.0945     0.033075   0.00496125]
 [0.04       0.1278     0.042012   0.02107782]
 [0.         0.0284     0.078736   0.02043116]]
**************************************************
Backtrace Table:
 [[0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 2.]]
**************************************************
Best Hidden Sequence q1q2q2q2
**************************************************
Probability of Observation Sequence: 0.04647023
